
export const GET_MOVIES = 'GET_MOVIES';
export const USERS_ERROR = 'USERS_ERROR'
export const WATCHED = 'WATCHED'
export const NOT_WATCHED = 'NOT_WATCHED'
export const FILTER_BY_VALUE = 'FILTER_BY_VALUE'
export const DATABASE_SET = 'DATABASE_SET'
export const SORT_BY = 'SORT_BY'
export const LOAD_DATA = 'LOAD_DATA'
export const LOAD_NEW_PAGE = 'LOAD_NEW_PAGE'
export const LOAD_EXACT_PAGE = 'LOAD_EXACT_PAGE'
export const MOVIES_PER_PAGE = 'MOVIES_PER_PAGE'
export const SET_FIRST_NAME = 'SET_FIRST_NAME'
export const SET_NEW_MOVIE = 'SET_NEW_MOVIE'
export const REMOVE_MOVIE = 'REMOVE_MOVIE'
export const CHANGE_THEME = 'CHANGE_THEME'
export const DATABASE_THEME_SET = 'DATABASE_THEME_SET'
export const GET_THEME = 'GET_THEME'
export const YOUR_RATING = 'YOUR_RATING'
export const DATE = 'DATE'
export const DATE_SET = 'DATE_SET'
export const GET_THEME_COLOR = 'GET_THEME_COLOR'
export const SET_DARK_MODE = 'SET_DARK_MODE'
export const DATABASE_DARK_MODE_SET = 'DATABASE_DARK_MODE_SET'
export const GET_DARK_MODE = 'GET_DARK_MODE'

